### PR TITLE
use avro library instead of avro-python3

### PR DESCRIPTION
**Pull request by hsheth2**

### CODE REVIEW

**Comment by ms32035** [comment]
@hsheth2 any eta when this would be merged?

**Comment by hsheth2** [comment]
I think this should be fine to merge. Thanks for pinging me @ms32035 - I had been waiting for some other changes to get merged in first and then totally forgot about this PR. 

@shirshanka let me know if you have any concerns, but otherwise let's merge this and cut a new release.

**Comment by ms32035** [comment]
@hsheth2 kindly asking again

**Review by shirshanka — APPROVED** [review]
LGTM

**Pull request merged**
